### ISSUE TITLE
Invalid next (SyntaxError)

### ISSUE THREAD

**Issue by rostgoat** [westonganger/rails_uuid_to_integer_primary_keys#1]
Hey @westonganger , thanks for this package!

I am attempting to use it locally in my project. I have copied your `migration.rb` into `lib/tasks` and renamed it to `lib/tasks/uuid_to_bigint.rb`.

I am starting off with two tables only, so I changed the glob to `app/models/{organization_impact,impact}.rb`.

I created a new migration and added the following line: `require Rails.root.join("lib/tasks/uuid_to_bigint.rb")`.

When I run the code, I get this error:

```bash
SyntaxError: /var/app/lib/tasks/uuid_to_bigint.rb:34: Invalid next (SyntaxError)
/var/app/lib/tasks/uuid_to_bigint.rb
Tasks: TOP => db:migrate
```

Coming from this line: `next if !primary_klass.table_exists?`

What am I doing wrong?

**Comment by westonganger** [comment]
Looks like there was a bug here from optimizing the code in this repo. I've just [pushed up a fix for this](https://github.com/westonganger/rails_uuid_to_integer_primary_keys/commit/402be2bdce1b63d8ad1471cbf1afbb9e1b82ce90). Can you try again?

All that was needed was to replace the `next` on that particular line with `return`

**Comment by westonganger** [comment]
@rostgoat Please let me know if the script is working well for you now.
