### ISSUE TITLE
`handle_normal_belongs_to` only takes 3 arguments

### ISSUE THREAD

**Issue by runephilosof-abtion** [westonganger/rails_uuid_to_integer_primary_keys#2]
`handle_normal_belongs_to` only takes 3 arguments, but it is called with 4.

https://github.com/westonganger/rails_uuid_to_integer_primary_keys/blob/4fe3f78c9a17a7575df6960e385f9ba290546e6b/migration.rb#L74

**Comment by westonganger** [comment]
This should now be fixed if you pull in the latest changes on master. Please confirm if this solves your issues.

**Comment by runephilosof-abtion** [comment]
Thanks.
